### ISSUE TITLE
/ban results in a crash

### ISSUE THREAD

**Issue by larssieboy18** [JavaFactoryDev/PunishControl-Wiki#4]
Hi,

Whenever I run /ban, it kicks me from my network. I run Waterfall 1.8-->1.14. Here is the error log: https://pastebin.com/LtiDwzKe. /ban randomplayer works fine tho. If you need any more information, please let me know!

**Comment by EsGibtKeineMitte** [comment]
Hi, thank you for using PunishControl,

And also thanks for reporting this error here & not somewhere else so we can fix it ASAP.
Are you using the latest version of Waterfall?
This errors usually happens when an outdated version of BungeeCord.
Also it would be helpful to know on which Version are you playing on & which java version you are using. 

Greetings, 
Leonhard | EsGibtKeineMitte

**Comment by larssieboy18** [comment]
Hi,

I'm using Waterfall build #293. Not an outdated one I would think. I'm playing on 1.14.4 with support up to 1.8 (ViaVersion) and tbh, I don't know which java version I use, as I'm using a shared host. I know for sure that I use at least Java 8.

By the way, I don't know if it helps, but when I do /unban {playername}, I get the following error: https://pastebin.com/sL0p4Wuz

**Comment by JavaFactoryDev** [comment]
This is not an error, it just happens if a command gets breaked up. Like when you are typing /unban and don't provide a player as an argument. This in most cases means that the player is not banned or doesn't exist.

Please try updating to Waterfall #295 we had issues exactly like that so it could help.

**Comment by JavaFactoryDev** [comment]
First of all: This bug only exists on 1.13+, for now, you could just play with 1.12.2 or older versions.

Also, this is NOT a bug caused by PunishControl but a bug caused by Protocolize. We are currently talking to the developer of Protocolize to fix this asap.

We are sorry for the inconvenience.

P.S. The second Pastebin link is no bug. It is just showing that this player doesn't seem to exist.

**Comment by larssieboy18** [comment]
Allright, thanks for the update! If possible, please mention me when it's fixed :)

Btw, the spigot page links to https://github.com/JavaFactoryDev/PunishControl-Wiki/releases/tag/1.03. This is not the same version as stated on the Spigot page so I don't think people get updates by downloading via spigot

**Comment by JavaFactoryDev** [comment]
We have fixed the issue:)
Also, the version 1.0.3 was edited by us to fix issues with older versions.

Greetings,
Leonhard
